# <p style="text-align:center;">__Numpy__</p>
## Basics of Numpy

In [13]:
import numpy as np

In [115]:
list1 = [1, 2, 3, 4, 5]
nparr1 = np.array(list1)

In [15]:
type(nparr1)

numpy.ndarray

In [16]:
nparr1

array([1, 2, 3, 4, 5])

In [23]:
nparr1.shape

(5,)

In [19]:
list2 = [23, 4, 53, 75, 72]
list3 = [924, 533, 253, 5424, 2452]
list4 = [list1, list2, list3]

nparr2 = np.array([list4])

In [20]:
nparr2

array([[[   1,    2,    3,    4,    5],
        [  23,    4,   53,   75,   72],
        [ 924,  533,  253, 5424, 2452]]])

In [21]:
type(nparr2)

numpy.ndarray

In [22]:
nparr2.shape

(1, 3, 5)

In [25]:
nparr3 = np.array([list1, list2, list3])

In [26]:
nparr3

array([[   1,    2,    3,    4,    5],
       [  23,    4,   53,   75,   72],
       [ 924,  533,  253, 5424, 2452]])

In [27]:
type(nparr3)

numpy.ndarray

In [28]:
nparr3.shape

(3, 5)

In [29]:
nparr2.reshape(5, 3, 1)

array([[[   1],
        [   2],
        [   3]],

       [[   4],
        [   5],
        [  23]],

       [[   4],
        [  53],
        [  75]],

       [[  72],
        [ 924],
        [ 533]],

       [[ 253],
        [5424],
        [2452]]])

In [30]:
nparr3.reshape(1, 15)

array([[   1,    2,    3,    4,    5,   23,    4,   53,   75,   72,  924,
         533,  253, 5424, 2452]])

In [46]:
nparr3.reshape(15, 1)

array([[   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [  23],
       [   4],
       [  53],
       [  75],
       [  72],
       [ 924],
       [ 533],
       [ 253],
       [5424],
       [2452]])

In [47]:
nparr4 = np.linspace(1, 50, 100)

In [48]:
nparr4

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [49]:
nparr4[24: 74] = 3.14

In [50]:
nparr4

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14      ,
        3.14      ,  3.14      ,  3.14      ,  3.14      ,  3.14

In [133]:
np1 = np.empty((2, 1, 2), dtype=int)
print(np1)

[[[0 0]]

 [[0 0]]]


In [119]:
np1.ndim

3

In [120]:
np1.shape

(2, 1, 2)

In [121]:
np1.size

4

In [122]:
np1.dtype

dtype('int64')

In [123]:
np1.itemsize

8

In [125]:
np1.data

In [139]:
print(dir(np.ctypeslib))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_concrete_ndptr', '_ctype_from_dtype', '_ctype_from_dtype_scalar', '_ctype_from_dtype_structured', '_ctype_from_dtype_subarray', '_ctype_ndarray', '_dtype', '_flagdict', '_flagnames', '_flags_fromnum', '_get_scalar_type_map', '_ndptr', '_ndptr_base', '_num_fromflags', '_pointer_type_cache', '_scalar_type_map', 'as_array', 'as_ctypes', 'as_ctypes_type', 'asarray', 'c_intp', 'ctypes', 'flagsobj', 'frombuffer', 'integer', 'load_library', 'ndarray', 'ndpointer', 'os']
